# Generated by Django 2.1.4 on 2019-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peering", "0044_auto_20190513_2153")]

    operations = [
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="is_direct_peer",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="is_route_monitor",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="internetexchangepeeringsession",
            name="is_route_server_peer",
            field=models.BooleanField(blank=True, default=False),
        )
    ]
